### ISSUE TITLE
Installation fails on ubuntu python3

### ISSUE THREAD

**Issue by devashishshankar** [smarie/python-pyfields#42]
Steps to reproduce (on docker):
```
docker pull ubuntu
docker run -it ubuntu bash

# Inside docker shell
apt-get -y update
apt-get install -y python python3 python-pip python3-pip
pip3 install pyfields
```

Stacktrace:
```
root@eddc884167cf:/# pip3 install pyfields
Collecting pyfields
  Downloading https://files.pythonhosted.org/packages/9f/4b/1e3eb1b5f35f51117d8b9801a4c051bdbc1b5d9889d1b48cdb056b1f7ec4/pyfields-0.12.0-py3-none-any.whl (43kB)
    100% |################################| 51kB 140kB/s
Collecting sentinel (from pyfields)
  Downloading https://files.pythonhosted.org/packages/2e/12/867f97b68c2a541f1e0de6b3b8ff52a2c2bef8d88228efc885ad07f20968/sentinel-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4q0121fl/sentinel/setup.py", line 5, in <module>
        long_description = readme.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 64: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4q0121fl/sentinel/
```

**Comment by devashishshankar** [comment]
Ok, so what fixed it was installing language packs before running pip install:

```
apt-get -y install language-pack-en
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
```

Reference: https://stackoverflow.com/questions/51026315/how-to-solve-unicodedecodeerror-in-python-3-6/51027262#51027262

However, still strange that this issue happens on vanilla ubuntu docker image.

**Comment by smarie** [comment]
It seems that this comes from the `sentinel` package, can you confirm that you reproduce the issue when you do `pip3 install sentinel` (without the language pack) ?

If so please confirm it directly on the issue I opened: https://github.com/eddieantonio/sentinel/issues/3

thanks!

**Comment by smarie** [comment]
The issue was solved by @eddieantonio and he made a new release of `sentinel`. Can you try again to confirm that the issue disappeared ? Thanks!

**Comment by devashishshankar** [comment]
Woah! Thanks for the quick fix @eddieantonio @smarie . It works now!

**Comment by smarie** [comment]
cool, thanks for the feedback!
